//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.Actors1 = new HashSet<Actor>();
            this.Actors = new HashSet<Actor>();
        }
    
        public int ActorId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Name { get; set; }
        public Nullable<int> ActorTypeId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> GlobalInfluence { get; set; }
    
        public virtual ICollection<Actor> Actors1 { get; set; }
        public virtual ICollection<Actor> Actors { get; set; }
        public virtual ActorType ActorType { get; set; }
    }
}
