//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AskStatus
    {
        public AskStatus()
        {
            this.Asks = new HashSet<Ask>();
        }
    
        public int AskStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Ask> Asks { get; set; }
    }
}
