//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventActor
    {
        public int EventActorId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> ActorId { get; set; }
        public int AttendingStatusId { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual AttendanceStatus AttendanceStatu { get; set; }
        public virtual EventActorAsk EventActorAsk { get; set; }
        public virtual Event Event { get; set; }
    }
}
