//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStatus
    {
        public EventStatus()
        {
            this.EventActors = new HashSet<EventActor>();
            this.Opportunities = new HashSet<Opportunity>();
            this.OpportunityActors = new HashSet<OpportunityActor>();
        }
    
        public int EventStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EventActor> EventActors { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<OpportunityActor> OpportunityActors { get; set; }
    }
}
