//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStatu
    {
        public EventStatu()
        {
            this.Opportunities = new HashSet<Opportunity>();
            this.Events = new HashSet<Event>();
        }
    
        public int EventStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
