//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectiveStatus
    {
        public ObjectiveStatus()
        {
            this.Objectives = new HashSet<Objective>();
        }
    
        public int ObjectiveStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Objective> Objectives { get; set; }
    }
}
