//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public Opinion()
        {
            this.ActorIssueOpinions = new HashSet<ActorIssueOpinion>();
            this.AskActors = new HashSet<AskActor>();
        }
    
        public int OpinionId { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
    
        public virtual ICollection<ActorIssueOpinion> ActorIssueOpinions { get; set; }
        public virtual ICollection<AskActor> AskActors { get; set; }
    }
}
