//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrevuEntities : DbContext
    {
        public PrevuEntities()
            : base("name=PrevuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActorIssueOpinion> ActorIssueOpinions { get; set; }
        public DbSet<Actor> Actors { get; set; }
        public DbSet<ActorType> ActorTypes { get; set; }
        public DbSet<AskActor> AskActors { get; set; }
        public DbSet<Ask> Asks { get; set; }
        public DbSet<AskStatus> AskStatuses { get; set; }
        public DbSet<AttendanceStatus> AttendanceStatus1 { get; set; }
        public DbSet<EventActorAsk> EventActorAsks { get; set; }
        public DbSet<EventActor> EventActors { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventStatus> EventStatus1 { get; set; }
        public DbSet<Issue> Issues { get; set; }
        public DbSet<Objective> Objectives { get; set; }
        public DbSet<ObjectiveStatus> ObjectiveStatuses { get; set; }
        public DbSet<Opinion> Opinions { get; set; }
        public DbSet<Opportunity> Opportunities { get; set; }
        public DbSet<OpportunityActor> OpportunityActors { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Department> Departments { get; set; }
    }
}
